### ISSUE TITLE
Error when make

### ISSUE THREAD

**Issue by anthonyrfarias** [wazo-platform/wazo-res-stasis-amqp#23]
Hello. I'm having an issue when i try to make within the directory. 

I get the following:

`cc -c -I../asterisk-amqp -DHAVE_STDINT_H=1 -Wall -Wextra -Wno-unused-parameter -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Winit-self -Wmissing-format-attribute -Wformat=2 -g -fPIC -D_GNU_SOURCE -D'AST_MODULE="res_stasis_amqp"' -D'AST_MODULE_SELF_SYM=__internal_res_stasis_amqp_self' -o res_stasis_amqp.o res_stasis_amqp.c
In file included from res_stasis_amqp.c:73:0:
res_stasis_amqp.c:699:3: error: ‘struct ast_module_info’ has no member named ‘requires’
  .requires = "res_stasis,res_amqp",
   ^
Makefile:38: recipe for target 'res_stasis_amqp.o' failed
make: *** [res_stasis_amqp.o] Error 1
`

What am i missing here?

**Comment by sboily** [comment]
Hello, what is your asterisk version headers?

**Comment by anthonyrfarias** [comment]
My Headers are like this: 

`Asterisk 17.4.0, Copyright (C) 1999 - 2018, Digium, Inc. and others.
Created by Mark Spencer <markster@digium.com>
Asterisk comes with ABSOLUTELY NO WARRANTY; type 'core show warranty' for details.
This is free software, with components licensed under the GNU General Public
License version 2 and other licenses; you are welcome to redistribute it under
certain conditions. Type 'core show license' for details.
=========================================================================
Running as user 'asterisk'
Running under group 'asterisk'
Connected to Asterisk 17.4.0 currently running on ZOOM-CloudPBX-Dev (pid = 8563)`

**Comment by anthonyrfarias** [comment]
I tried the installation with asterisk 16.10 and now when i try to load the module `module load res_amqp.so` asterisk shutsdown and won't start until the module is removed from /usr/lib/asterisk/modules/. Only after removing it, asterisk starts normally

**Comment by anthonyrfarias** [comment]
I manage to finally make it work with asterisk 16.10. I think there is some kind of trouble with asterisk 17. It works for me anyway. Thanks.
